import { createSlice } from '@reduxjs/toolkit';
import { getAllCars } from './operations';

const handleRejected = (state, action) => {
  state.isLoading = false;
  state.error = action.payload;
};

const handlePending = state => {
  state.isLoading = true;
};

const initialState = {
  allCars: [],
  isLoading: false,
  error: null,
};

const carsSlice = createSlice({
  name: 'cars',
  initialState,
  extraReducers: builder => {
    builder
      .addCase(getAllCars.pending, handlePending)
      .addCase(getAllCars.fulfilled, (state, { payload }) => {
        state.isLoading = false;
        state.error = null;
        state.allCars = payload;
      })
      .addCase(getAllCars.rejected, handleRejected);
  },
});

export const carsReducer = carsSlice.reducer;

// [
//   {
//     id: 9001,
//     year: 2008,
//     make: 'Buick',
//     model: 'Enclave',
//     type: 'SUV',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697014249/Cars/iuifk2twzpf0lv0bnmvd.jpg',
//     description:
//       'The Buick Enclave is a stylish and spacious SUV known for its comfortable ride and luxurious features.',
//     fuelConsumption: '10.5',
//     engineSize: '3.6L V6',
//     accessories: ['Leather seats', 'Panoramic sunroof', 'Premium audio system'],
//     functionalities: [
//       'Power liftgate',
//       'Remote start',
//       'Blind-spot monitoring',
//     ],
//     rentalPrice: '$40',
//     rentalCompany: 'Luxury Car Rentals',
//     address: '123 Example Street, Kiev, Ukraine',
//     rentalConditions:
//       "Minimum age: 25\nValid driver's license\nSecurity deposit required",
//     mileage: 5858,
//   },
//   {
//     id: 9002,
//     year: 2019,
//     make: 'Volvo',
//     model: 'XC90',
//     type: 'SUV',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697014254/Cars/k7vqjcmvcqxpqoiaavrl.webp',
//     description:
//       'The Volvo XC90 is a premium SUV that offers exceptional safety, advanced technology, and elegant design.',
//     fuelConsumption: '8.3',
//     engineSize: '2.0L 4-cylinder',
//     accessories: [
//       'Nappa leather seats',
//       'Bowers & Wilkins premium sound system',
//       'Head-up display',
//     ],
//     functionalities: [
//       'IntelliSafe advanced safety features',
//       'Pilot Assist semi-autonomous driving',
//       'Four-zone automatic climate control',
//     ],
//     rentalPrice: '$50',
//     rentalCompany: 'Premium Auto Rentals',
//     address: '456 Example Avenue, Lviv, Ukraine',
//     rentalConditions:
//       "Minimum age: 21\nValid driver's license\nProof of insurance required",
//     mileage: 5352,
//   },
//   {
//     id: 9003,
//     year: 2020,
//     make: 'Volvo',
//     model: 'XC60',
//     type: 'SUV',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697014444/Cars/qqzuhu6qmi3gibf3p649.jpg',
//     description:
//       'The Volvo XC60 is a compact luxury SUV with a beautiful interior, strong performance, and advanced safety features.',
//     fuelConsumption: '7.9',
//     engineSize: '2.0L 4-cylinder',
//     accessories: [
//       'Premium leather seats',
//       'Harman Kardon audio system',
//       'Hands-free power tailgate',
//     ],
//     functionalities: [
//       'City Safety collision avoidance technology',
//       'Pilot Assist with adaptive cruise control',
//       '9-inch Sensus touchscreen infotainment system',
//     ],
//     rentalPrice: '$45',
//     rentalCompany: 'Luxury Car Rentals',
//     address: '789 Example Boulevard, Odessa, Ukraine',
//     rentalConditions:
//       "Minimum age: 23\nValid driver's license\nCredit card required",
//     mileage: 5966,
//   },
//   {
//     id: 9004,
//     year: 2006,
//     make: 'HUMMER',
//     model: 'H2',
//     type: 'SUV',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697014874/Cars/e0wsv0qr7ilrqbfvazsp.jpg',
//     description:
//       'The HUMMER H2 is a rugged and powerful SUV that stands out with its imposing presence and off-road capabilities.',
//     fuelConsumption: '19.8',
//     engineSize: '6.0L V8',
//     accessories: [
//       'Heated leather seats',
//       'Bose premium sound system',
//       'Off-road package',
//     ],
//     functionalities: [
//       'Electronic locking front and rear differentials',
//       'Stabilitrak stability control',
//       'Tire pressure monitoring system',
//     ],
//     rentalPrice: '$55',
//     rentalCompany: 'Adventure Car Rentals',
//     address: '321 Example Road, Kharkiv, Ukraine',
//     rentalConditions:
//       "Minimum age: 25\nValid driver's license\nSecurity deposit required",
//     mileage: 4771,
//   },
//   {
//     id: 9005,
//     year: 2016,
//     make: 'Subaru',
//     model: 'Outback',
//     type: 'SUV',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697014967/Cars/abbtkp4kme98ifzg4zln.jpg',
//     description:
//       'The Subaru Outback is a versatile and reliable SUV that combines off-road capability with a comfortable and spacious interior.',
//     fuelConsumption: '8.7',
//     engineSize: '2.5L 4-cylinder',
//     accessories: [
//       'Leather upholstery',
//       'Power moonroof',
//       'Harman Kardon premium audio system',
//     ],
//     functionalities: [
//       'Symmetrical All-Wheel Drive',
//       'X-Mode off-road assist',
//       'Subaru EyeSight driver-assist system',
//     ],
//     rentalPrice: '$35',
//     rentalCompany: 'Adventure Car Rentals',
//     address: '987 Example Street, Kyiv, Ukraine',
//     rentalConditions:
//       "Minimum age: 21\nValid driver's license\nCredit card required",
//     mileage: 4061,
//   },
//   {
//     id: 9006,
//     year: 2010,
//     make: 'Mitsubishi',
//     model: 'Outlander',
//     type: 'SUV',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697015095/Cars/wuvmpts8eh8jkuu0xzbf.jpg',
//     description:
//       'The Mitsubishi Outlander is a practical and fuel-efficient SUV with a stylish design and a range of modern features.',
//     fuelConsumption: '7.9',
//     engineSize: '2.4L 4-cylinder',
//     accessories: [
//       'Heated front seats',
//       'Rockford Fosgate premium audio system',
//       'Power liftgate',
//     ],
//     functionalities: [
//       'Super All-Wheel Control',
//       'Multi-View camera system',
//       'Bluetooth hands-free system',
//     ],
//     rentalPrice: '$30',
//     rentalCompany: 'City Car Rentals',
//     address: '654 Example Avenue, Lviv, Ukraine',
//     rentalConditions:
//       "Minimum age: 21\nValid driver's license\nProof of insurance required",
//     mileage: 5374,
//   },
//   {
//     id: 9007,
//     year: 2014,
//     make: 'Nissan',
//     model: 'Pathfinder',
//     type: 'SUV',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697015188/Cars/wdbjvcvk2dwglehxtnby.jpg',
//     description:
//       'The Nissan Pathfinder is a versatile and family-friendly SUV that offers a comfortable ride and generous cargo space.',
//     fuelConsumption: '9.5',
//     engineSize: '3.5L V6',
//     accessories: [
//       'Tri-Zone Automatic Climate Control',
//       'Bose premium audio system',
//       'Rear-seat entertainment system',
//     ],
//     functionalities: [
//       'Intelligent 4x4 system',
//       'Advanced Drive-Assist Display',
//       'Nissan Intelligent Key with push-button ignition',
//     ],
//     rentalPrice: '$40',
//     rentalCompany: 'Luxury Car Rentals',
//     address: '321 Example Road, Odessa, Ukraine',
//     rentalConditions:
//       "Minimum age: 25\nValid driver's license\nSecurity deposit required",
//     mileage: 6282,
//   },
//   {
//     id: 9008,
//     year: 2009,
//     make: 'Lincoln',
//     model: 'Navigator L',
//     type: 'SUV',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697015292/Cars/vxe8y0kfypvyebfizeg9.jpg',
//     description:
//       'The Lincoln Navigator L is a luxurious and spacious SUV with a refined interior and advanced technology features.',
//     fuelConsumption: '18.2',
//     engineSize: '5.4L V8',
//     accessories: [
//       'Premium leather seats',
//       'THX II Certified audio system',
//       'Power-deployable running boards',
//     ],
//     functionalities: [
//       'AdvanceTrac with Roll Stability Control',
//       'Voice-Activated Navigation System',
//       'Power liftgate',
//     ],
//     rentalPrice: '$50',
//     rentalCompany: 'Elite Car Rentals',
//     address: '123 Example Boulevard, Kharkiv, Ukraine',
//     rentalConditions:
//       "Minimum age: 25\nValid driver's license\nInsurance coverage required",
//     mileage: 6173,
//   },
//   {
//     id: 9009,
//     year: 2000,
//     make: 'GMC',
//     model: 'Yukon Denali',
//     type: 'SUV',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697015403/Cars/pg5cwztslelz24lu9rde.webp',
//     description:
//       'The GMC Yukon Denali is a full-size luxury SUV that offers a powerful engine, a comfortable and spacious interior, and a host of advanced features.',
//     fuelConsumption: '14.5',
//     engineSize: '6.0L V8',
//     accessories: [
//       'Heated and ventilated front seats',
//       'BOSE premium sound system',
//       'Power-folding third-row seats',
//     ],
//     functionalities: [
//       'All-Wheel Drive',
//       'Adaptive suspension',
//       'Advanced safety features',
//     ],
//     rentalPrice: '$45',
//     rentalCompany: 'Premium Car Rentals',
//     address: '789 Example Square, Dnipro, Ukraine',
//     rentalConditions:
//       "Minimum age: 25\nValid driver's license\nSecurity deposit required",
//     mileage: 4989,
//   },
//   {
//     id: 9010,
//     year: 2007,
//     make: 'Hyundai',
//     model: 'Tucson',
//     type: 'SUV',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697015621/Cars/yztuwtjdqnboyct4n2ai.jpg',
//     description:
//       'The Hyundai Tucson is a reliable and fuel-efficient SUV that combines practicality with a stylish design and a comfortable ride.',
//     fuelConsumption: '8.2',
//     engineSize: '2.0L 4-cylinder',
//     accessories: [
//       'Apple CarPlay and Android Auto integration',
//       'Blind Spot Detection',
//       'Hands-free smart liftgate',
//     ],
//     functionalities: [
//       'Front-Wheel Drive',
//       'Hillstart Assist Control',
//       'LED headlights',
//     ],
//     rentalPrice: '$25',
//     rentalCompany: 'Economy Car Rentals',
//     address: '456 Example Lane, Zaporizhzhia, Ukraine',
//     rentalConditions:
//       "Minimum age: 21\nValid driver's license\nCredit card required",
//     mileage: 4591,
//   },
//   {
//     id: 9011,
//     year: 2006,
//     make: 'MINI',
//     model: 'Convertible',
//     type: 'Convertible',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697015727/Cars/emeachdnar8kadqdujm0.jpg',
//     description:
//       'The MINI Convertible is a compact and fun-to-drive convertible that offers a unique and iconic design, agile handling, and an open-air driving experience.',
//     fuelConsumption: '6.9',
//     engineSize: '1.6L 4-cylinder',
//     accessories: [
//       'Convertible soft top',
//       'Sport seats',
//       'MINI Connected infotainment system',
//     ],
//     functionalities: [
//       'Front-Wheel Drive',
//       'Dynamic Stability Control',
//       'Rain-sensing wipers',
//     ],
//     rentalPrice: '$30',
//     rentalCompany: 'Fun Car Rentals',
//     address: '234 Example Place, Vinnytsia, Ukraine',
//     rentalConditions:
//       "Minimum age: 21\nValid driver's license\nProof of insurance required",
//     mileage: 6275,
//   },
//   {
//     id: 9012,
//     year: 2007,
//     make: 'Bentley',
//     model: 'Azure',
//     type: 'Convertible',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697015797/Cars/wixua1iaujjmjps3d3wz.jpg',
//     description:
//       'The Bentley Azure is a luxurious and prestigious convertible that combines exceptional craftsmanship, powerful performance, and sophisticated elegance.',
//     fuelConsumption: '22.5',
//     engineSize: '6.8L V8',
//     accessories: [
//       'Mulliner Driving Specification',
//       'Naim for Bentley premium audio system',
//       'Heated steering wheel',
//     ],
//     functionalities: [
//       'Rear-Wheel Drive',
//       'Air suspension',
//       'Automatic convertible roof',
//     ],
//     rentalPrice: '$150',
//     rentalCompany: 'Luxury Car Rentals',
//     address: '567 Example Street, Lviv, Ukraine',
//     rentalConditions:
//       "Minimum age: 30\nValid driver's license\nSecurity deposit and insurance required",
//     mileage: 4317,
//   },
//   {
//     id: 9013,
//     year: 2004,
//     make: 'Mercedes-Benz',
//     model: 'SL-Class',
//     type: 'Convertible',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697015912/Cars/fkfzkscfij1tvyo1wvz8.jpg',
//     description:
//       'The Mercedes-Benz SL-Class is a legendary luxury convertible that offers a perfect blend of thrilling performance, advanced technology, and opulent comfort.',
//     fuelConsumption: '11.8',
//     engineSize: '5.0L V8',
//     accessories: [
//       'Airscarf neck-level heating',
//       'Harman Kardon premium audio system',
//       'Active Body Control suspension',
//     ],
//     functionalities: [
//       'Rear-Wheel Drive',
//       'Retractable hardtop roof',
//       'Multi-contour seats',
//     ],
//     rentalPrice: '$75',
//     rentalCompany: 'Exquisite Car Rentals',
//     address: '789 Example Boulevard, Kyiv, Ukraine',
//     rentalConditions:
//       "Minimum age: 25\nValid driver's license\nSecurity deposit and proof of insurance required",
//     mileage: 5722,
//   },
//   {
//     id: 9014,
//     year: 2010,
//     make: 'Aston Martin',
//     model: 'DBS',
//     type: 'Convertible',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697016039/Cars/jytzqjtm7pn40guhnxrr.jpg',
//     description:
//       'The Aston Martin DBS is a stunning and high-performance convertible that exemplifies British luxury and delivers exhilarating driving dynamics.',
//     fuelConsumption: '16.5',
//     engineSize: '6.0L V12',
//     accessories: [
//       'Carbon Ceramic brakes',
//       'Bang & Olufsen BeoSound audio system',
//       'Bridge of Weir leather upholstery',
//     ],
//     functionalities: [
//       'Rear-Wheel Drive',
//       'Carbon-fiber body panels',
//       'Adaptive Damping System',
//     ],
//     rentalPrice: '$200',
//     rentalCompany: 'Supreme Car Rentals',
//     address: '123 Example Avenue, Odessa, Ukraine',
//     rentalConditions:
//       "Minimum age: 30\nValid driver's license\nSecurity deposit and insurance required",
//     mileage: 6464,
//   },
//   {
//     id: 9015,
//     year: 1996,
//     make: 'Pontiac',
//     model: 'Firebird',
//     type: 'Convertible',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697016195/Cars/ycf1gedxcfwnc6evjesd.jpg',
//     description:
//       'The Pontiac Firebird is a classic American muscle car with bold styling, powerful engines, and an iconic presence that captures the essence of the golden era of performance.',
//     fuelConsumption: '15.2',
//     engineSize: '5.7L V8',
//     accessories: [
//       'T-Top roof',
//       'Delco premium audio system',
//       'Sport suspension',
//     ],
//     functionalities: [
//       'Rear-Wheel Drive',
//       'Limited-slip differential',
//       'High-performance exhaust',
//     ],
//     rentalPrice: '$50',
//     rentalCompany: 'Classic Car Rentals',
//     address: '456 Example Street, Lviv, Ukraine',
//     rentalConditions:
//       "Minimum age: 25\nValid driver's license\nSecurity deposit required",
//     mileage: 5091,
//   },
//   {
//     id: 9016,
//     year: 2009,
//     make: 'Lamborghini',
//     model: 'Murcielago',
//     type: 'Convertible',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697016280/Cars/v8ffysrqkb9ps6k3dhfx.jpg',
//     description:
//       'The Lamborghini Murcielago is an exotic and high-performance convertible that represents the epitome of Italian automotive engineering, combining breathtaking design, blistering speed, and a spine-tingling exhaust note.',
//     fuelConsumption: '25.0',
//     engineSize: '6.5L V12',
//     accessories: [
//       'Carbon-fiber body panels',
//       'Alcantara upholstery',
//       'Lamborghini Infotainment System',
//     ],
//     functionalities: [
//       'All-Wheel Drive',
//       'Electronic Stability Control',
//       'Retractable soft-top roof',
//     ],
//     rentalPrice: '$500',
//     rentalCompany: 'Supercar Rentals',
//     address: '321 Example Road, Kharkiv, Ukraine',
//     rentalConditions:
//       "Minimum age: 30\nValid driver's license\nSecurity deposit and insurance required",
//     mileage: 5832,
//   },
//   {
//     id: 9017,
//     year: 2011,
//     make: 'Audi',
//     model: 'A5',
//     type: 'Convertible',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697016338/Cars/bsx6wblny3ritjzjk89e.jpg',
//     description:
//       'The Audi A5 is a stylish and refined convertible that offers a perfect blend of elegance, cutting-edge technology, and exhilarating driving dynamics.',
//     fuelConsumption: '8.5',
//     engineSize: '2.0L Inline-4',
//     accessories: [
//       'Bang & Olufsen 3D sound system',
//       'Audi Virtual Cockpit',
//       'Audi Drive Select',
//     ],
//     functionalities: [
//       'Front-Wheel Drive',
//       'Quattro all-wheel drive available',
//       'Power-folding acoustic soft-top',
//     ],
//     rentalPrice: '$150',
//     rentalCompany: 'Luxury Car Rentals',
//     address: '987 Example Lane, Dnipro, Ukraine',
//     rentalConditions:
//       "Minimum age: 25\nValid driver's license\nSecurity deposit and insurance required",
//     mileage: 4635,
//   },
//   {
//     id: 9018,
//     year: 2001,
//     make: 'BMW',
//     model: 'Z8',
//     type: 'Convertible',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697016418/Cars/i1bp2njp6w5rcbusvfbb.jpg',
//     description:
//       'The BMW Z8 is a classic and timeless convertible that combines iconic retro-inspired design, outstanding performance, and luxurious comfort.',
//     fuelConsumption: '14.2',
//     engineSize: '4.9L V8',
//     accessories: [
//       'Aluminum space frame',
//       'Nappa leather upholstery',
//       'Harman Kardon audio system',
//     ],
//     functionalities: [
//       'Rear-Wheel Drive',
//       'Dynamic Stability Control',
//       'Power-operated soft-top roof',
//     ],
//     rentalPrice: '$300',
//     rentalCompany: 'Classic Car Rentals',
//     address: '654 Example Circle, Zaporizhzhia, Ukraine',
//     rentalConditions:
//       "Minimum age: 25\nValid driver's license\nSecurity deposit and proof of insurance required",
//     mileage: 5990,
//   },
//   {
//     id: 9019,
//     year: 1998,
//     make: 'Chevrolet',
//     model: 'Camaro',
//     type: 'Convertible',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697016480/Cars/znm737y6t7ikhcgepzcn.jpg',
//     description:
//       'The Chevrolet Camaro is an American muscle car legend with a rich heritage, boasting aggressive styling, powerful engines, and exhilarating performance.',
//     fuelConsumption: '13.5',
//     engineSize: '5.7L V8',
//     accessories: [
//       'Leather upholstery',
//       'Bose premium sound system',
//       'Performance suspension',
//     ],
//     functionalities: [
//       'Rear-Wheel Drive',
//       'Limited-slip differential',
//       'Power-operated convertible top',
//     ],
//     rentalPrice: '$200',
//     rentalCompany: 'Muscle Car Rentals',
//     address: '123 Example Street, Lviv, Ukraine',
//     rentalConditions:
//       "Minimum age: 25\nValid driver's license\nSecurity deposit and insurance required",
//     mileage: 6330,
//   },
//   {
//     id: 9020,
//     year: 2006,
//     make: 'Mercedes-Benz',
//     model: 'SLK',
//     type: 'Convertible',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697016570/Cars/rorapy0ac7jsyrfzczmf.jpg',
//     description:
//       'The Mercedes-Benz SLK-Class is a luxurious and sporty convertible that offers a perfect balance of style, performance, and refinement, delivering an enjoyable open-top driving experience.',
//     fuelConsumption: '9.8',
//     engineSize: '3.5L V6',
//     accessories: [
//       'Airscarf neck-level heating',
//       'Harman Kardon surround sound system',
//       'Magic Sky Control panoramic roof',
//     ],
//     functionalities: [
//       'Rear-Wheel Drive',
//       'Dynamic Stability Control',
//       'Retractable hardtop roof',
//     ],
//     rentalPrice: '$250',
//     rentalCompany: 'Luxury Car Rentals',
//     address: '456 Example Avenue, Kyiv, Ukraine',
//     rentalConditions:
//       "Minimum age: 25\nValid driver's license\nSecurity deposit and insurance required",
//     mileage: 6280,
//   },
//   {
//     id: 9021,
//     year: 2020,
//     make: 'Chrysler',
//     model: 'Voyager',
//     type: 'Van/Minivan',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697016979/Cars/o8ah8twn09hzhzc87ezs.jpg',
//     description:
//       'The Chrysler Voyager is a practical and versatile van/minivan that provides comfortable seating, ample cargo space, and a range of convenient features for family-oriented transportation.',
//     fuelConsumption: '8.2',
//     engineSize: '3.6L V6',
//     accessories: [
//       "Stow 'n Go seating",
//       'Uconnect infotainment system',
//       'Blind Spot Monitoring',
//     ],
//     functionalities: [
//       'Front-Wheel Drive',
//       'Electronic Stability Control',
//       'Power sliding side doors',
//     ],
//     rentalPrice: '$100',
//     rentalCompany: 'Family Car Rentals',
//     address: '789 Example Boulevard, Odesa, Ukraine',
//     rentalConditions:
//       "Minimum age: 21\nValid driver's license\nSecurity deposit and insurance required",
//     mileage: 5807,
//   },
//   {
//     id: 9022,
//     year: 2020,
//     make: 'Kia',
//     model: 'Rio',
//     type: 'Hatchback',
//     img: 'https://res.cloudinary.com/ditdqzoio/image/upload/v1687252635/cars/kia_rio_hatchback.jpg',
//     description:
//       'The Kia Rio is a compact and fuel-efficient hatchback that offers a blend of affordability, reliability, and practicality, making it an excellent choice for urban commuting and everyday driving.',
//     fuelConsumption: '6.2',
//     engineSize: '1.6L 4-cylinder',
//     accessories: [
//       'Apple CarPlay and Android Auto integration',
//       'Smart Key with Push Button Start',
//       'Automatic climate control',
//     ],
//     functionalities: [
//       'Front-Wheel Drive',
//       'Electronic Stability Control',
//       'Rearview camera',
//     ],
//     rentalPrice: '$50',
//     rentalCompany: 'Economy Car Rentals',
//     address: '321 Example Lane, Kharkiv, Ukraine',
//     rentalConditions:
//       "Minimum age: 21\nValid driver's license\nSecurity deposit and insurance required",
//     mileage: 4618,
//   },
//   {
//     id: 9023,
//     year: 2020,
//     make: 'Volvo',
//     model: 'XC60',
//     type: 'SUV',
//     img: 'https://res.cloudinary.com/dhhr00mg7/image/upload/v1697014254/Cars/k7vqjcmvcqxpqoiaavrl.webp',
//     description:
//       'The Volvo XC60 is a luxurious and versatile SUV that combines Scandinavian design, advanced safety features, and a comfortable driving experience, making it an ideal choice for families and adventure enthusiasts.',
//     fuelConsumption: '8.5',
//     engineSize: '2.0L 4-cylinder',
//     accessories: [
//       'Leather upholstery',
//       'Panoramic sunroof',
//       'Harman Kardon premium sound system',
//     ],
//     functionalities: [
//       'All-Wheel Drive',
//       'City Safety collision avoidance technology',
//       'Power tailgate',
//     ],
//     rentalPrice: '$150',
//     rentalCompany: 'Premium Car Rentals',
//     address: '987 Example Road, Dnipro, Ukraine',
//     rentalConditions:
//       "Minimum age: 25\nValid driver's license\nSecurity deposit and insurance required",
//     mileage: 6618,
//   },
//   {
//     id: 9024,
//     year: 2020,
//     make: 'Land Rover',
//     model: ' Sport',
//     type: 'SUV',
//     img: 'https://res.cloudinary.com/ditdqzoio/image/upload/v1687252635/cars/land_rover_range_rover_sport.jpg',
//     description:
//       'The Land Rover Range Rover Sport is a premium SUV that offers a perfect blend of luxury, off-road capability, and dynamic performance, providing a refined driving experience both on and off the road.',
//     fuelConsumption: '11.8',
//     engineSize: '3.0L V6',
//     accessories: [
//       'Premium Windsor leather seats',
//       'Meridian surround sound system',
//       'Adaptive Dynamics suspension',
//     ],
//     functionalities: [
//       'All-Wheel Drive',
//       'Terrain Response 2 system',
//       'Power-operated gesture tailgate',
//     ],
//     rentalPrice: '$300',
//     rentalCompany: 'Luxury SUV Rentals',
//     address: '654 Example Street, Lviv, Ukraine',
//     rentalConditions:
//       "Minimum age: 25\nValid driver's license\nSecurity deposit and insurance required",
//     mileage: 4856,
//   },
//   {
//     id: 9025,
//     year: 2020,
//     make: 'Kia',
//     model: 'Rio',
//     type: 'Sedan, Hatchback',
//     img: 'https://res.cloudinary.com/ditdqzoio/image/upload/v1687252635/cars/kia_rio_sedan_hatchback.jpg',
//     description:
//       'The Kia Rio is a versatile and fuel-efficient vehicle available in both sedan and hatchback body styles, offering a comfortable cabin, modern features, and a smooth driving experience, making it an attractive choice for urban commuters.',
//     fuelConsumption: '6.2',
//     engineSize: '1.6L 4-cylinder',
//     accessories: [
//       'Apple CarPlay and Android Auto integration',
//       'Smart Key with Push Button Start',
//       'Automatic climate control',
//     ],
//     functionalities: [
//       'Front-Wheel Drive',
//       'Electronic Stability Control',
//       'Rearview camera',
//     ],
//     rentalPrice: '$50',
//     rentalCompany: 'Economy Car Rentals',
//     address: '321 Example Lane, Kharkiv, Ukraine',
//     rentalConditions:
//       "Minimum age: 21\nValid driver's license\nSecurity deposit and insurance required",
//     mileage: 8234,
//   },
//   {
//     id: 9026,
//     year: 2021,
//     make: 'Kia',
//     model: 'Rio',
//     type: 'Sedan, Hatchback',
//     img: 'https://res.cloudinary.com/ditdqzoio/image/upload/v1687252635/cars/kia_rio_sedan_hatchback.jpg',
//     description:
//       'The Kia Rio is a versatile and fuel-efficient vehicle available in both sedan and hatchback body styles, offering a comfortable cabin, modern features, and a smooth driving experience, making it an attractive choice for urban commuters.',
//     fuelConsumption: '6.2',
//     engineSize: '1.6L 4-cylinder',
//     accessories: [
//       'Apple CarPlay and Android Auto integration',
//       'Smart Key with Push Button Start',
//       'Automatic climate control',
//     ],
//     functionalities: [
//       'Front-Wheel Drive',
//       'Electronic Stability Control',
//       'Rearview camera',
//     ],
//     rentalPrice: '$50',
//     rentalCompany: 'Economy Car Rentals',
//     address: '321 Example Lane, Kharkiv, Ukraine',
//     rentalConditions:
//       "Minimum age: 21\nValid driver's license\nSecurity deposit and insurance required",
//     mileage: 6234,
//   },
//   {
//     year: 34,
//     make: 'make 9027',
//     model: 'model 9027',
//     type: 'type 9027',
//     img: 'img 9027',
//     description: 'description 9027',
//     fuelConsumption: 'fuelConsumption 9027',
//     engineSize: 'engineSize 9027',
//     accessories: [],
//     functionalities: [],
//     rentalPrice: 'rentalPrice 9027',
//     rentalCompany: 'rentalCompany 9027',
//     address: 'address 9027',
//     rentalConditions: 'rentalConditions 9027',
//     mileage: 90,
//     id: '9027',
//   },
//   {
//     year: 6,
//     make: 'make 9028',
//     model: 'model 9028',
//     type: 'type 9028',
//     img: 'img 9028',
//     description: 'description 9028',
//     fuelConsumption: 'fuelConsumption 9028',
//     engineSize: 'engineSize 9028',
//     accessories: [],
//     functionalities: [],
//     rentalPrice: 'rentalPrice 9028',
//     rentalCompany: 'rentalCompany 9028',
//     address: 'address 9028',
//     rentalConditions: 'rentalConditions 9028',
//     mileage: 94,
//     id: '9028',
//   },
//   {
//     year: 21,
//     make: 'make 9029',
//     model: 'model 9029',
//     type: 'type 9029',
//     img: 'img 9029',
//     description: 'description 9029',
//     fuelConsumption: 'fuelConsumption 9029',
//     engineSize: 'engineSize 9029',
//     accessories: [],
//     functionalities: [],
//     rentalPrice: 'rentalPrice 9029',
//     rentalCompany: 'rentalCompany 9029',
//     address: 'address 9029',
//     rentalConditions: 'rentalConditions 9029',
//     mileage: 35,
//     id: '9029',
//   },
//   {
//     year: 88,
//     make: 'make 9030',
//     model: 'model 9030',
//     type: 'type 9030',
//     img: 'img 9030',
//     description: 'description 9030',
//     fuelConsumption: 'fuelConsumption 9030',
//     engineSize: 'engineSize 9030',
//     accessories: [],
//     functionalities: [],
//     rentalPrice: 'rentalPrice 9030',
//     rentalCompany: 'rentalCompany 9030',
//     address: 'address 9030',
//     rentalConditions: 'rentalConditions 9030',
//     mileage: 5,
//     id: '9030',
//   },
//   {
//     year: 54,
//     make: 'make 9031',
//     model: 'model 9031',
//     type: 'type 9031',
//     img: 'img 9031',
//     description: 'description 9031',
//     fuelConsumption: 'fuelConsumption 9031',
//     engineSize: 'engineSize 9031',
//     accessories: [],
//     functionalities: [],
//     rentalPrice: 'rentalPrice 9031',
//     rentalCompany: 'rentalCompany 9031',
//     address: 'address 9031',
//     rentalConditions: 'rentalConditions 9031',
//     mileage: 73,
//     id: '9031',
//   },
//   {
//     year: 51,
//     make: 'make 9032',
//     model: 'model 9032',
//     type: 'type 9032',
//     img: 'img 9032',
//     description: 'description 9032',
//     fuelConsumption: 'fuelConsumption 9032',
//     engineSize: 'engineSize 9032',
//     accessories: [],
//     functionalities: [],
//     rentalPrice: 'rentalPrice 9032',
//     rentalCompany: 'rentalCompany 9032',
//     address: 'address 9032',
//     rentalConditions: 'rentalConditions 9032',
//     mileage: 6,
//     id: '9032',
//   },
// ];
